name: Test Pipeline

on:
  push:
    branches:
      - master

jobs:
  master_docker_build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Speed up checkout

      - name: Debug Repository Structure
        run: ls -R

      - name: Build Backend Docker Image
        run: |
          docker build --cache-from=backend-image:latest -f backend/Dockerfile -t backend-image:latest ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build --cache-from=frontend-image:latest -f frontend/Dockerfile -t frontend-image:latest ./frontend

  master_docker_deploy:
    runs-on: self-hosted
    needs: master_docker_build
    steps:
      - name: Clean Up Old Containers
        run: |
          docker stop backend-container frontend-container || true
          docker rm backend-container frontend-container || true
          docker network prune -f
          docker system prune -af

      - name: Create Docker Network (if not exists)
        run: docker network create app-network || true

      - name: Run Backend Container
        run: docker run -d --name backend-container -p 5000:5000 --network app-network backend-image:latest

      - name: Run Frontend Container
        run: docker run -d --name frontend-container -p 3000:3000 --network app-network frontend-image:latest
